# Generated by Django 4.1.3 on 2022-11-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publication_year', models.DateTimeField()),
                ('publisher', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('small_image_url', models.CharField(max_length=100)),
                ('medium_image_url', models.CharField(max_length=100)),
                ('large_image_url', models.CharField(max_length=100)),
            ],
        ),
    ]
