# Generated by Django 4.1.3 on 2022-11-28 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('birth_date', models.DateTimeField()),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('member_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('memebership_type', models.CharField(max_length=50)),
                ('borrowed_books', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrow_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('issue', models.CharField(max_length=150)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Librarian.book')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Librarian.member')),
            ],
        ),
    ]
